test_apig_wsgi.py
* Use just one WSGI app in a pytest fixture
* Test more paths, more obviously in AAA pattern
=> Improve tests

apig_wsgi.py, test_apig_wsgi.py
Thanks @kthhrv for trying it out.
=> A couple fixes from in-situ testing

HISTORY.rst, README.rst, apig_wsgi.py, test_apig_wsgi.py
=> Add binary response support

HISTORY.rst, apig_wsgi.py, test_apig_wsgi.py
Fix crashes for POST when binary support is on.
=> Work with base64 encoded bodies

HISTORY.rst, apig_wsgi.py, test_apig_wsgi.py
=> Support exc_info by re-raising the exception

setup.py
=> Remove coding and future headers in setup.py

HISTORY.rst, apig_wsgi.py, test_apig_wsgi.py
=> Change statusCode to an integer

HISTORY.rst, apig_wsgi.py, test_apig_wsgi.py
=> Add statusDescription to output

HISTORY.rst, apig_wsgi.py, test_apig_wsgi.py
Revert #54 because it turns out it breaks API Gateway.
=> Revert adding statusDescription to output

HISTORY.rst
=> Fix ALB integer release note

setup.cfg, setup.py
Realized it was missing in #69.
=> Multilint setup.py

HISTORY.rst, apig_wsgi.py, test_apig_wsgi.py
=> Add support for gzip/binary response with plain text content-type

HISTORY.rst, tests/test_apig_wsgi.py
=> Improve URL encoding tests and add HISTORY note

HISTORY.rst, README.rst, example/app/testapp/views.py, example/deployment/playbook.yml, pyproject.toml, src/apig_wsgi.py, tests/test_apig_wsgi.py
Fixes #103.
Also add apig_wsgi.full_event to the environ.
=> Support multi-value headers and query params

.travis.yml, HISTORY.rst, README.rst, example/README.rst, tox.ini
As per [Brett Cannon's article](https://snarky.ca/why-you-should-use-python-m-pip/).
=> Switch 'pip install' for 'python -m pip install'

src/apig_wsgi.py, tests/test_apig_wsgi.py
=> Fix passing Content-Type and Host headers in environ

.pre-commit-config.yaml, example/deployment/files/cloudformation_site.yml
More code quality checks. Also migrate to top-level map config.
=> Add pre-commit-hooks

src/apig_wsgi.py, tests/test_apig_wsgi.py
=> Namespace v1 tests

example/README.rst, example/app/requirements.txt, example/deployment/files/cloudformation_site.yml, example/deployment/playbook.yml, example/deployment/requirements.txt
Use the latest versions of Python and dependencies, and use the v2 format for the HTTP API, for #124.
=> Update example app

src/apig_wsgi.py
As per Hynek's article, this can be dangerous: https://hynek.me/articles/hasattr/
=> Remove hasattr() call

example/README.rst, example/deployment/files/cloudformation_site.yml, example/deployment/playbook.yml
Python 3.9 is not available yet.
=> Use Python 3.8 in example Lambda

HISTORY.rst, src/apig_wsgi.py, tests/test_apig_wsgi.py
=> Fix query string parameter encoding

HISTORY.rst, example/README.rst, example/deployment/files/cloudformation_site.yml, example/deployment/playbook.yml, src/apig_wsgi.py, tests/test_apig_wsgi.py
=> Fix handling of query string encoding in ALB deployments

HISTORY.rst, src/apig_wsgi/__init__.py, tests/test_apig_wsgi.py
=> Handle requestContext being None

example/app/manage.py, example/app/testapp/settings.py, example/app/testapp/tests.py, example/app/testapp/urls.py, example/app/testapp/views.py, example/app/testapp/wsgi.py, pyproject.toml, requirements/compile.py, setup.py, src/apig_wsgi/__init__.py, tests/test_apig_wsgi.py
=> Add __future__.annotations to all files

CHANGELOG.rst, src/apig_wsgi/__init__.py, tests/test_apig_wsgi.py
=> Enable binary support by default for ALB events

.pre-commit-config.yaml, .typos.toml, README.rst, example/README.rst
This tool corrects common misspellings in all kinds of text files.
=> Add typos tool to pre-commit
